### ISSUE TITLE
Border gap around deepin windows when using tiling application like quicktile

### ISSUE THREAD

**Issue by Skillzore** [linuxdeepin/deepin-wm#16]
When using a tiling application like quicktile, the deepin windows like terminal and file manager does not fill their tile space completely. They leave a border around them.
[Picture 1](https://imgur.com/6I9CixP)
[Picture 2](https://imgur.com/pJ9V1V4)

At first I thought it was the [GTK issue of client side decorations](https://wiki.archlinux.org/index.php/GTK%2B#Client-side_decorations), but adding the fix gtk.css file did not fix the issue. There is also a [Manjaro thread on the issue](https://forum.manjaro.org/t/basic-tiling-feature-for-deepin/25557/3). 

Would be nice if this could be fixed. It is a bit annoying to not be able to fully tile the deepin terminal and instead have to use my mouse to tile it. And then it is only tileable to half my desktop.

**Comment by sonald** [comment]
which version or distribution do you use ? I can not reproduce the problem on deepin 15.4.1.

**Comment by Skillzore** [comment]
Well, I am running Arch:
`Linux Archer 4.13.3-1-ARCH #1 SMP PREEMPT Thu Sep 21 20:33:16 CEST 2017 x86_64 GNU/Linux`
and have installed the latest deepin group: [https://www.archlinux.org/groups/x86_64/deepin/](https://www.archlinux.org/groups/x86_64/deepin/)
which means version 15.4.1
![deepinversion](https://user-images.githubusercontent.com/13891190/31383665-2c5f2966-adbc-11e7-928c-fe1fbeac0fe7.png)

I am also using quicktile v0.3 when tiling.

**Comment by Skillzore** [comment]
Maybe @ssokolow, creator of quicktile, could have an idea to what is causing this?
Would also be nice if tiling like this could be implemented in deepin as default, maybe use quicktile to do it? It is open source after all, https://github.com/ssokolow/quicktile.

**Comment by ssokolow** [comment]
If it were only the terminals, I'd suspect it to be a pathological side-effect of QuickTile not yet taking sizing hints into account (ie. QuickTile just assumes that a window will wind up at the size it asked for).

However, since no file manager I'm aware of requests that it be resized in increments, that throws that theoery out.

Beyond that, I wouldn't know without more research (that I won't have time to do until I've rewritten several websites before my host's pricing model changes on December 1st) because I've just been operating on the assumption that relying on libwnck to both retrieve and set window geometry would prevent this kind of problem.

(libwnck is a GNOME-family library specifically intended to hide the warts and weird corner cases of asking the WM to manipulate windows and I switched to it after I got fed up with windows having so many conflicting conceptions of "my geometry".)

**Comment by Skillzore** [comment]
Alright, thanks for the insight!

I'll happily provide more info or test things if needed, in the mean time I'll have to live with it.

All things deepin are affected, terminal, file manager, archive manager, image viewer, calendar and even the boot maker. The calendar and boot maker are not re-sizable though, so they behave weird anyway.

It might be between deepin and quicktile or it might be between deepin and another pagackage, while using quicktile. But it is deepin, all other programs work just fine. Chrome, libre office, atom, electron, gimp, the list goes on. 
(Even though gimp is not re-sizing properly, but it fills its tilespace as it should).

@sonald Let me know if you need any more info or need me to try something! I'll gladly help out.

**Comment by Skillzore** [comment]
Some new info, it seems that [evince](https://wiki.gnome.org/Apps/Evince) has the same issue as the deepin apps/window manager. So what do they have in common that would cause this behavior?

**Comment by ssokolow** [comment]
There's a lot they have in common. The problem is that it only becomes a useful data point when we can rule out all of the things they *don't* have in common with the applications which don't exhibit the problem.

Since it's something that'd be exposed to the WM, there are two things I can think of which might help to narrow it down:

1. Run `xprop` on various windows to see how the ones with and without the problem differ. (This can be done now)
2. Write a tool which draws differently coloured boxes around the top-level window (should snugly enclose the window decorations) and the client window (should follow the border between the window decorations and window content) to either rule out or confirm libwnck seeing the unwanted space as part of the window somehow. (This I'm not sure when I'll have time for.)

**Comment by sonald** [comment]
@Skillzore  still, I can not reproduce any of visual problems you encounter.  @felixonmars did you experience any of these?

**Comment by felixonmars** [comment]
I do not use a tiling window manager, but didn't reproduce the problem using kwin's place window.

**Comment by ssokolow** [comment]
One thing that did just occur to me. Is it possible that "All things deepin" are based on GTK+ 3.x and everything else except Evince is GTK+ 2.x? (I know GIMP hasn't released a GTK+ 3.x release yet.)

(One of the simplest ways to check is probably to compare the Open/Save dialogs, since GTK+ 3.x "improved" them.)

If so, that'd bring it back to "What is GTK+ 3.x doing differently?"

**Comment by sonald** [comment]
@ssokolow I do not quite understand what you are saying.

**Comment by ssokolow** [comment]
Because not everything has been migrated from GTK+ 2.x to GTK+ 3.x yet, desktops tend to contain a mix of programs using both... and just like Qt, GTK+ 3.x can't use GTK+ 2.x themes... you just have to write two different versions of the same theme.

(eg. I'm running Lubuntu 14.04 LTS because I haven't had time to squash the new bugs a *buntu upgrade inevitably brings, and GIMP is still on GTK+ 2.x, but File Roller has been ported to GTK+ 3.x.)

It's possible that QuickTile has no problem with GTK+ 2.x apps and no problem with how my GTK+ 3.x theme is set up, but something about the deepin setup causes GTK+ 3.x apps to confuse it.

**Comment by Skillzore** [comment]
@sonald @ssokolow Alright, so I compared the "open dialog" of Chrome (works fine with quicktile) and the open dialog of Evince (which leaves a border with quicktile), and [they are identical](https://imgur.com/UGdK6Wi), looks almost like they are handled by Deepin. Also, both the dialogs tile just fine with quicktile, which is weird since their respective programs don't behave the same. If deepin handles the dialog, it is also weird that they tile fine. This just leads to more questions than answers...

**Comment by ssokolow** [comment]
GIMP's is the GTK+ 2.x one while Chrome and Evince are using GTK+ 3.x.

The problem with using Chrome for comparison is that neither Chrome nor Firefox are really "GTK+ 3.x apps"... they use their own internal GUI tookits and integrate with GTK+ just enough to get things like standard Open/Save dialogs.

I know File Roller was already using GTK+ 3.x in 2014 Lubuntu (among other reasons, it has a bug that causes it to show both the regular menu bar and the one intended to be gobbled up by Client-Side Decorations), so I'd suggest double-checking its Open/Save dialog to confirm that and then seeing if it exhibits the same problem as Evince.

**Comment by Skillzore** [comment]
Chrome handles correctly even with enabling "Use system title bar and borders".

File Roller, called Archive Manager in Deepin, handles badly with a border. Does look more and more like [the GTK+ issue I mentioned in my first post](https://wiki.archlinux.org/index.php/GTK%2B#Client-side_decorations), but how come the fix .css file didn't work?

**Comment by ssokolow** [comment]
> but how come the fix .css file didn't work?

That, I'm not sure about... but it doesn't bode well for QuickTile if it *is* the client-side decorations, since, with all of this fancy stuff being recent, it's possible I won't be able to find an API that lets me get the window dimensions with the shadows removed.

As for why I didn't run into the problem and fix it already, I haven't had time to upgrade from Lubuntu 14.04 LTS, so I'm still on GTK+ 3.10.8 while CSD wasn't introduced until 3.12.

**Comment by Skillzore** [comment]
Alright, I guess I'll dig into the GTK issue more and try to find another workaround. Maybe just downgrading my GTK version?

Also, maybe we should somehow move this thread to quicktile instead? It is not a Deepin issue after all.

**Comment by robclancy** [comment]
@sonald this is due to the shadows around certain deepin apps. that area is seen as part of the application to tiling managers. I have the same issue on i3. so being able to turn off the shadows would solve this.

**Comment by deceptikon** [comment]
This thread definitely shouldn't have been closed or moved to quicktile.
It is not related to quicktile at all, have exactly the same problem with i3wm

**Comment by abelsiqueira** [comment]
I also have the problem on i3.
